### ISSUE TITLE
Date within the text in rounding.pdf

### ISSUE THREAD

**Issue by erhant** [higham/what-is#1]
Dear Prof. Higham, 

In the [PDF of rounding](https://github.com/higham/what-is/blob/master/rounding.pdf), right after the ending of the first paragraph under **Round to Nearest** section, instead of _What happens if the two candidate numbers are equally close?_ (as it appears on [https://nhigham.com/2020/04/](https://nhigham.com/2020/04/)) it says _What happens if the two candidate Tuesday April 28, 2020numbers are equally close?_. It seems the appearance of the date was an error.

Thank you for your amazing informative texts, they are very helpful!
Best,
Erhan

**Comment by higham** [comment]
I think I fixed this but forgot to reply to say I had done so.
