### ISSUE TITLE
How are defined `e` and `e_1` in circulant.pdf (both vectors? e1 scalar?)?

### ISSUE THREAD

**Issue by vadimkantorov** [higham/what-is#3]
There's a comma after e1, it may be that some part of text defining e_1 was cut off inadvertently.

Thanks!

**Comment by higham** [comment]
Thanks - I've update the document.

**Comment by vadimkantorov** [comment]
the first unit vector is a vector (1, 0, 0, ..., 0)^T?

**Comment by higham** [comment]
Yes.
